{% set name = "linopy" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/linopy-{{ version }}.tar.gz
  sha256: abc0e776878064eee2174afbc8900f679f902d8ff5c7037ef620280e44e8447f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - numpy
    - scipy
    - bottleneck
    - toolz
    - numexpr
    - xarray >=2022.9.0
    - dask-core >=0.18.0
    - tqdm
    - deprecation

test:
  imports:
    - linopy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyPSA/linopy
  summary: Linear optimization with N-D labeled arrays in Python
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fabianhofmann
    - fneum
