{% set name = "linopy" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/linopy-{{ version }}.tar.gz
  sha256: c8d421bd37ecff383e602a15097aa3c05943d564cf9b7fd0246ba81595a3dbac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2,<8
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy
    - bottleneck
    - toolz
    - numexpr
    - xarray >=2023.9.0
    - dask-core >=0.18.0
    - tqdm
    - deprecation

test:
  imports:
    - linopy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyPSA/linopy
  summary: Linear optimization with N-D labeled arrays in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/PyPSA/linopy
  doc_url: https://github.com/PyPSA/linopy/blob/master/README.md

extra:
  recipe-maintainers:
    - fabianhofmann
    - fneum
    - xylar
