{% set name = "linopy" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/linopy-{{ version }}.tar.gz
  sha256: 7c8c913018478171a0ef8002abe121571fad73ca940ed2db450908d1881bb0df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=60
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    # the stricter constraint on numpy for python 3.10
    - numpy <2.0
    - scipy
    - bottleneck
    - toolz
    - numexpr
    - xarray >=2024.2.0
    - dask-core >=0.18.0
    - polars
    - tqdm
    - deprecation

test:
  imports:
    - linopy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/PyPSA/linopy
  summary: Linear optimization with N-D labeled arrays in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/PyPSA/linopy
  doc_url: https://github.com/PyPSA/linopy/blob/master/README.md

extra:
  recipe-maintainers:
    - fabianhofmann
    - fneum
    - xylar
    - lkstrp
