# override python >=3.11 so we can drop numpy <2 constraint
schema_version: 1

context:
  name: linopy
  version: 0.6.2
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/linopy-${{ version }}.tar.gz
  sha256: 2347305a0d3d78a54e7df5012c659989ae766254a4046b4318607e1d009848a2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=60
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - numpy <2
    - scipy
    - bottleneck
    - toolz
    - numexpr
    - xarray >=2024.2.0
    - dask-core >=0.18.0
    - polars >=1.31
    - tqdm
    - deprecation
    - google-cloud-storage
    - requests
    - packaging
tests:
  - python:
      imports:
        - linopy
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Linear optimization with N-D labeled arrays in Python
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/PyPSA/linopy
  repository: https://github.com/PyPSA/linopy
  documentation: https://github.com/PyPSA/linopy/blob/master/README.md

extra:
  recipe-maintainers:
    - fabianhofmann
    - fneum
    - xylar
    - lkstrp
